### PR TITLE
Remove webui

### PR DESCRIPTION
**Pull request by iBobik**
Postgres has no web ui, so do not offer button to it.

### CODE REVIEW

**Comment by iBobik** [comment]
I am not sure if my change is related to the fail.

**Comment by alexbelgium** [comment]
Looks like the fail is due to the build script so not relevant here. Thanks very much for the PR!

**Comment by alexbelgium** [comment]
I wanted to implement an admin app such as padmin but it didn't seem easy to do...

**Comment by iBobik** [comment]
I also like the idea of having webui, but I think it is not worth the maintenance and additional memory - most users will need to just set one password and default database for that one app they need it. Others can use one of the many GUI clients remotely connected.

**Pull request merged**
