### PR TITLE
OPENPROJECT | Update to 14.1.0

### PR DESCRIPTION
**Pull request by baldarn**
Update to 14.1.0

### CODE REVIEW

**Comment by baldarn** [comment]
@alexbelgium I think is me, but the docker image is not build
Screenshot_20240522_111944

maybe with the automerge this is not triggered?

**Comment by alexbelgium** [comment]
Build is not completed yet? You can check in the Actions if it was completef

**Comment by baldarn** [comment]
mmmm I think that wasn't triggered

when should that be triggered? on merge

**Comment by baldarn** [comment]
@alexbelgium how did you fix this? so next time I'll try to do without messing with you ;)

**Comment by alexbelgium** [comment]
hehe I forced the image update by changing the addon version number :-) I didn't check but we can see at your next automerge if it starts the script correctly :-)

**Pull request merged**
