### PR TITLE
Sponserblock Fix startup script

### PR DESCRIPTION
**Pull request by bruvv**
Should fix https://github.com/alexbelgium/hassio-addons/issues/959 did not test it yet.

### CODE REVIEW

**Comment by alexbelgium** [comment]
Hi, thanks! The linter complains about one element could you please fix it before I merge? Thanks! 

2023-08-25 09:58:27 [ERROR]   Error code: 1. Command output:
------

/github/workspace/sponsorblockcast/config.json
  27:5  error  Duplicate key 'CSS_PLAYING_INTERVAL'  jsonc/no-dupe-keys

✖ 1 problem (1 error, 0 warnings)
------

**Comment by bruvv** [comment]
Done, I think we should check this tho, I have not tested this yet. but if you merge it I can check it right away, my weekend has started :)

**Comment by alexbelgium** [comment]
Thanks!

**Comment by bruvv** [comment]
Tested and working :)

**Comment by alexbelgium** [comment]
You're the best thanks!

**Pull request merged**
