### PR TITLE
onpr_check-pr.yaml: Remove `runs-on` from check-build

### PR DESCRIPTION
**Pull request by reedy**
https://github.com/alexbelgium/hassio-addons/issues/967

### CODE REVIEW

**Comment by reedy** [comment]
Looks like the job now correctly skips...

Screenshot 2023-08-27 at 15 16 40

**Comment by reedy** [comment]
https://github.com/alexbelgium/hassio-addons/commit/b1be295225cfd6d641958c20d834df276c302104

**Comment by alexbelgium** [comment]
Hi, sorry I hadn't seen your PR

The source of the issue is that a few days ago I wanted to call the build workflow directly but actually it is a bad idea as it would perform the commits instead of just testing the build.

I'll change the logic again then to avoid calling the main build workflow

**Comment by alexbelgium** [comment]
The issue with the previous logic code is that it tried to watch for the config.json/yaml file which is not strictly required as the Dockerfile can build from a BUILD directive directly.

**Pull request closed without merging**
