### PR TITLE
Navidrome startup and config

### PR DESCRIPTION
**Pull request by arunanbala**
- Reduced access to media to read-only as write permissions are not required https://www.navidrome.org/docs/usage/security/#permissions
- Set the web UI link to use the default port
- Make config options work by splitting default values and schemas
- Exclude the cache from backups
- Expose more Navidrome config options
- Explicitly export shell variables for Navidrome to pick up

### CODE REVIEW

**Comment by arunanbala** [comment]
The data folder location has changed, but as the config options never actually made it to the running server then no users should have been able to start it up with the old value.

**Comment by alexbelgium** [comment]
Hi, thanks very much! shouldn't the variables be exported with `export xxx` to be available in navidrome?

**Comment by arunanbala** [comment]
I thought so too, but I did have Navidrome start up without export in there and correctly accept the config value for my music collection. I don't fully understand the interplay of containers with local addon development (I'm copying files to the addons share) so willing to believe my setup does something different to the release images.

I have added export in 634eae780 anyway as it won't hurt and will mean nobody will ask if export is needed in future.

**Comment by arunanbala** [comment]
The original commit added lint errors, so have repushed as a87bf89a7

**Comment by arunanbala** [comment]
For the record, the release version of this is crashing for me in a way I didn't see with local testing:

time="2024-08-20T19:44:55Z" level=info msg="Creating DB Schema"
time="2024-08-20T19:44:57Z" level=info msg="Starting signaler"
time="2024-08-20T19:44:57Z" level=error msg="Agent not available. Check configuration" name=lastfm
time="2024-08-20T19:44:57Z" level=error msg="Agent not available. Check configuration" name=spotify
time="2024-08-20T19:44:57Z" level=info msg="Creating Image cache" maxSize="250 MB" path=/data/cache/images
time="2024-08-20T19:44:57Z" level=info msg="Configuring Media Folder" name="Music Library" path=/media/music
time="2024-08-20T19:44:57Z" level=info msg="Found ffmpeg" path=/usr/bin/ffmpeg
time="2024-08-20T19:44:57Z" level=info msg="Finished initializing cache" cache=Image elapsedTime=3.1ms maxSize=250MB
time="2024-08-20T19:44:57Z" level=info msg="Running initial setup"
time="2024-08-20T19:44:57Z" level=info msg="Creating new JWT secret, used for encrypting UI sessions"
time="2024-08-20T19:44:57Z" level=info msg="Setting Session Timeout" value=24h
panic: chi: routing pattern must begin with '/' in 'localhost/api/events'

goroutine 128 [running]:
github.com/go-chi/chi/v5.(*Mux).handle(0xc00003c948?, 0x14?, {0xc00003c948?, 0x1?}, {0x7f3778160668?, 0xc000448030?})
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:403 +0x2c5
github.com/go-chi/chi/v5.(*Mux).Handle(0xc0000af740, {0xc00003c948, 0x14}, {0x7f3778160668, 0xc000448030})
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:116 +0x9f
github.com/navidrome/navidrome/server.(*Server).initRoutes.func1({0x27a2058, 0xc0000af740})
	/__w/navidrome/navidrome/server/server.go:185 +0x1f4
github.com/go-chi/chi/v5.(*Mux).Group(0x278f320?, 0xc000a09e40)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:271 +0x38
github.com/navidrome/navidrome/server.(*Server).initRoutes(0xc0001b2000)
	/__w/navidrome/navidrome/server/server.go:181 +0x354
github.com/navidrome/navidrome/server.New({0x279f8a0, 0xc0000aa290}, {0x2791a68, 0xc000448030})
	/__w/navidrome/navidrome/server/server.go:40 +0xe8
github.com/navidrome/navidrome/cmd.CreateServer({0x0?, 0x0?})
	/__w/navidrome/navidrome/cmd/wire_gen.go:35 +0xaa
github.com/navidrome/navidrome/cmd.runNavidrome.startServer.func1()
	/__w/navidrome/navidrome/cmd/root.go:103 +0x38
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
	/go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x96
Error : /etc/cont-init.d/99-run.sh exiting 2

With my local testing, the path was showing as /api/events and I don't know why localhost got prepended now.
Navidrome is at least picking up the config option for the path to the music library, so that's good.
I will try to understand what is happening and attempt a fix later this week.

**Pull request merged**
