### PR TITLE
Initialize Gluetun

### PR DESCRIPTION
**Pull request by BeachyHeadCode**
This is untested but the majority of the environment vars for the docker have been added per the wiki here: https://github.com/qdm12/gluetun-wiki/tree/main#table-of-contents

Unsure if I created all of the dockerfile scripts that are required and removed the ones not needed.

Implementing issue #734

TODO:
- [x] Create files.
- [x] Verify container obtains injected files.
- [ ] Verify injected files function as intended.
- [ ] Release for review

### CODE REVIEW

**Comment by MrPlow254** [comment]
@alexbelgium is there a way to test build the existing dockerfile without having it look for a project on this repo? I have a local-addon loaded in HA throwing this error:

`Can't install ghcr.io/alexbelgium/gluetun-armv7:3.35.0: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=3.35.0&fromImage=ghcr.io%2Falexbelgium%2Fgluetun-armv7&platform=linux%2Farm%2Fv7: Internal Server Error ("Head "https://ghcr.io/v2/alexbelgium/gluetun-armv7/manifests/3.35.0": denied")`

Not fully understanding the documentation from HA https://github.com/home-assistant/builder in comparison to how projects are set up on this repo.

**Comment by alexbelgium** [comment]
Hi, thanks! Just delete the image tag in the config.json and it will locally build :) haven't had time to check your work yet thanks!

**Comment by MrPlow254** [comment]
Is it possible to use translations? https://github.com/home-assistant/addons/blob/master/mariadb/translations/en.yaml

I also need to do research on how to override the network mode for the docker services. For example Jackett plugin currently uses port 9117. That needs to be bypassed and a network mode needs to be set to Gluetun to pass all traffic through this addon. Very simple to do with a container file but as you mentioned in #734 HA isn't meant to adjust this way out of the box.

**Comment by alexbelgium** [comment]
Hi, of course, translations work nice. I had removed them as my repo was too big and caused issues, however for a single addon it should be fine

Regarding your point about ports, HA actually allows port mapping in the same way as a composer file : if in the Jackett addon configuration you specify a different port, this will be the one exposed to the outside. The only case when it doesn't work is if the addon is using the host network - the mapping then doesn't work and the original port is forced

**Comment by alexbelgium** [comment]
Would you want me to first the current version in the repo to see how it goes ? We can put a disclaimer in the name (such as DONTUSE) to prevent people from trying it before it is completed and complaining :-)

**Comment by MrPlow254** [comment]
I don't think it is ready yet to complete the pull request.

I will verify the mapping suggestion you made. So essentially what you are saying for example with Jacket:

1. Jacket addon container specifies 9117 internally.
2. HA maps Jacket externally to port 9000 in this example.
3. HA maps Gluetun maps port 9000 externally.
4. Gluten addon container specifies 9117 internally.

I'm unsure if this process then throws the output into a single port to the external internet. I have not tested Gluetun in HA other than getting the installer and config working. I do have Gluetun working in a composer file on the same machine.

**Comment by MrPlow254** [comment]
Well pushed all the config changes and fixed Gluetun not having permissions for networking.

Set up the config file how I want it however i am getting a funky error:
image

The OpenVPN username the environment variable OPENVPN_USER is set yet the container is saying it isn't set. Is there something I am missing? Do we just need to define the environment variable in the config.json file?

**Comment by MrPlow254** [comment]
Well pushed all the config changes and fixed Gluetun not having permissions for networking.

Set up the config file how I want it however i am getting a funky error:
image

The OpenVPN username the environment variable OPENVPN_USER is set yet the container is saying it isn't set. Is there something I am missing? Do we just need to define the environment variable in the config.json file?

**Comment by alexbelgium** [comment]
> I don't think it is ready yet to complete the pull request.
> 
> I will verify the mapping suggestion you made. So essentially what you are saying for example with Jacket:
> 
> 1. Jacket addon container specifies 9117 internally.
> 2. HA maps Jacket externally to port 9000 in this example.
> 3. HA maps Gluetun maps port 9000 externally.
> 4. Gluten addon container specifies 9117 internally.
> 
> I'm unsure if this process then throws the output into a single port to the external internet. I have not tested Gluetun in HA other than getting the installer and config working. I do have Gluetun working in a composer file on the same machine.

Hi, this is exactly how it works, in the end it's just like a docker compose. As long as the host network option is not used in config.json

**Comment by alexbelgium** [comment]
> Well pushed all the config changes and fixed Gluetun not having permissions for networking.
> 
> Set up the config file how I want it however i am getting a funky error: image
> 
> The OpenVPN username the environment variable OPENVPN_USER is set yet the container is saying it isn't set. Is there something I am missing? Do we just need to define the environment variable in the config.json file?
> 
> It is also not creating the /config/addons_config/gluetun folder so i am unable to link that with the containers /gluetun/ directory.

Did you map the config folder in config.json? Here is an example : https://github.com/alexbelgium/hassio-addons/blob/534b65c4635614917530c181bfdc52ddc10cb3f9/baikal/config.json#L58-L62

I've checked and actually the upstream image entrypoint doesn't use /etc/cont-init.d but directly executes a script : https://github.com/qdm12/gluetun/blob/1ac031e78c5cc1732bcab4781ace85939eebdee6/Dockerfile#L202

Either you need to inject your scripts by modifying the file /gluetun-entrypoint (for example you inject your code execution wirh `sed -i "1a /./etc/cont-init.d/20-folders.sh" /gluetun-entrypoint` or more easily in those circumstances I use a custom launch script. If you add this file to your addon : https://github.com/alexbelgium/hassio-addons/blob/master/fireflyiii/rootfs/entrypoint.sh,  modify the dockerfile to launch it : https://github.com/alexbelgium/hassio-addons/blob/534b65c4635614917530c181bfdc52ddc10cb3f9/fireflyiii/Dockerfile#L80-L82, then create a file named 90-run.sh to run the previous script. Your run.sh can be as light as : 
```
#!/bin/bash

/./gluetun-entrypoint
```

Also, variables defined in the addon options are just put in a file named /data/config.json (or something likes that). You need to use to then pass the variables to your script. Either it is done manually, or you can use my global_variables script. To do that, just add `00-global_var.sh` to the modules as here : https://github.com/alexbelgium/hassio-addons/blob/534b65c4635614917530c181bfdc52ddc10cb3f9/fireflyiii/Dockerfile#L54 and it will execute a script that will take all your addon options and pass them as env variables to the app

**Comment by MrPlow254** [comment]
@alexbelgium I am aimlessly attempting to figure this out lol. Adding the CMD /entrypoint.sh prompts in the log it does not exist. So it seems the COPY rootfs/ / does nothing

**Comment by MrPlow254** [comment]
I was able to tinker around with this and verify that the files are getting added into the container. However, The log does not output the correct information and the config file is still not updating the container environment variables.

image

20-folder.sh and 90-run.sh both are functioning correctly themselves.

**Pull request closed without merging**
