### PR TITLE
Mailer security changed

### PR DESCRIPTION
**Pull request by NODeeJay**
Hi Alex,

with version 2.7 the variable was changed from MAILER_SECURE to MAILER_SECURITY and now it accepts a string with either tls, starttls, or none.

I hope I found it everywhere :-)

### CODE REVIEW

**Comment by alexbelgium** [comment]
Thanks! You'll just also need to increment the version in config.json `"version": "2.9.7-3",` to allow the new version to be shown in HA

**Comment by NODeeJay** [comment]
Will it be then a 2.9.8 (following Semantic versioning) or 2.9.7-4?

**Comment by alexbelgium** [comment]
> 

In my naming convention, I align with the upstream app. It is still at 2.9.7, so I usually increment by adding something after this number. Thus my 2.9.7-3 that doesn't follow semantic versioning, but that will be replaced by 2.9.8 as soon as it is emitted by the upstream maintainer

**Comment by alexbelgium** [comment]
Thanks! As I saw in the readme that there were only 3 possible values for the new parameter, I've made it a list instead of a str. Don't hesitate to change back if this is not correct

**Comment by NODeeJay** [comment]
List is a good idea, thanks, did not consider that. Anything left or shall we release it?

**Comment by alexbelgium** [comment]
Perfect, thanks!

**Pull request merged**
