### PR TITLE
Multiple external disk mounting capability

### PR DESCRIPTION
**Pull request by elmerenges**
I just tweaked your code, now it is possible to mount multiple external shares.
It is backward compatible with the previous versions.

### CODE REVIEW

**Comment by alexbelgium** [comment]
Thanks! I'll merge this and update the version to allow people to update

**Comment by alexbelgium** [comment]
I've also added a code to mount smbv1 shares : it is an optional boolean in config.json. If checked, then in 50-mounts the code is added to cifs mounts.

Thanks again for helping making those addons better!

**Comment by alexbelgium** [comment]
Hi, I have made some changes to the code to make it more compatible following an issue with a user. Due to this, there are two breaking changes : multiple network disks must be separated by a "," and they are mounted to a folder with the name of the external share.

**Comment by brewcrawler** [comment]
It's a reasonable change. I was super lazy with my PR, just wanted it to work somehow. This version is much nicer.

**Comment by elmerenges** [comment]
It's a reasonable change. I was super lazy with my PR, just wanted it to work somehow. This version is much nicer.

**Comment by alexbelgium** [comment]
No I really appreciate your work and that you took the time for the PR !

Actually someone had trouble mounting his smb drive, and in the other code I had implemented a sequential testing of all cifs versions and securities until it works... And this allowed him to mount the smb drive.

But please if there was another option that I removed when changing the code please tell me and I'll adapt

Have a nice day

**Comment by elmerenges** [comment]
I think the current approach is better then the previous.
I updated both Radarr and Sonarr, and the additional tinkering with my previous remote mount settings took about 5-10 minute, so I am happy :)

Thank you for the addons, they saved me from some headache.

**Comment by alexbelgium** [comment]
btw I've added a new addon from the same lineage, prowlarr. As I understand, it is an help program for Radarr and Sonarr "Prowlarr is a indexer manager/proxy built on the popular arr .net/reactjs base stack to integrate with your various PVR apps. Prowlarr supports both Torrent Trackers and Usenet Indexers. It integrates seamlessly with Sonarr, Radarr, Lidarr, and Readarr offering complete management of your indexers with no per app Indexer setup required (we do it all)."

**Pull request merged**
