### PR TITLE
update photoprism

### PR DESCRIPTION
**Pull request by baldarn**

### CODE REVIEW

**Comment by baldarn** [comment]
I'm not 100% this is going to work, can you check? thanks!

**Comment by alexbelgium** [comment]
Hi, currently it's pulling the "preview" tag so no need to fix a specific tag. The update is done periodically

**Comment by alexbelgium** [comment]
Thanks!

**Comment by baldarn** [comment]
sorry to bother, wouldn't be better to tag to a specific image tag? like this the behavior is unpredictable :/

**Comment by alexbelgium** [comment]
I was thinking that always pulling the "preview" or "latest" tag ensured a consistency in quality ? Rather than individual tags for which it is much more complex to automate

**Pull request merged**
