### PR TITLE
Add discovery to Mealie config

### PR DESCRIPTION
**Pull request by andrew-codechimp**
Integrations can support discovery of add-ons if the add-on supports it.

Adding discovery for Mealie so that the integration can detect the add-on and suggest a setup.  Note this is not in place within the integration at the moment as needs the discovery tag into the add-on to detect this, I am not an add-on dev so have been unable to work out where to add this into my own config to test.

See adguard example of where this has been added.
https://github.com/hassio-addons/addon-adguard-home/blob/f7d3615c616d942ef150e7bc0afc5a1c9e4060bc/adguard/config.yaml#L25

### CODE REVIEW

**Comment by alexbelgium** [comment]
Hi, thanks actually this is an undocumented feature :
image https://developers.home-assistant.io/docs/add-ons/configuration/

I will still push it in a test version and we'll see!

**Comment by andrew-codechimp** [comment]
Yes, it seems the docs need updating as I've come across a few that do this.
Once the test version is available I'll work on the integration side to see if I can get it working.

**Comment by alexbelgium** [comment]
Thanks for the pointer!

**Comment by joostlek** [comment]
I checked with Stefan from the supervisor, and apparently we also need a script that publishes the data to the integration. Adguard has that located here https://github.com/hassio-addons/addon-adguard-home/tree/main/adguard/rootfs/etc/s6-overlay/s6-rc.d/discovery

**Comment by andrew-codechimp** [comment]
Looking at the history of adguard there is an older discovery implementation that follows the cont-init.d pattern used here, not sure if this could be dropped in and just the `service adguard` reference changed.

https://github.com/hassio-addons/addon-adguard-home/blob/f6dbb7dbdece33d58ea298dac2af06853505e1c8/adguard/rootfs/etc/cont-init.d/discovery.sh

**Pull request merged**
