### PR TITLE
OPENPROJECT | Fix start

### PR DESCRIPTION
**Pull request by baldarn**
fixing start entrypoint of openproject

### CODE REVIEW

**Comment by baldarn** [comment]
@alexbelgium maybe I can't `automerge` :)

**Comment by baldarn** [comment]
`/automerge`

**Comment by baldarn** [comment]
mmm had a problem

https://github.com/alexbelgium/hassio-addons/actions/runs/9155794783/job/25168864224

**Comment by alexbelgium** [comment]
argh it used to work :-) /automerge

**Comment by alexbelgium** [comment]
now with workflow reverted before versions update
/automerge

**Pull request merged**
