### PR TITLE
[Tandoor_Recipes] add externalfiles and option to disable debug mode.

### PR DESCRIPTION
**Pull request by nough**
One of the reasons that Vabene1111 created tandoor recipes was to store and order external recipe files. I have a set of a good few of these that i'd like to access via Tandoor, so I thought I'd add in the bits needed to store these properly from the home assistant addon in local storage.

To be honest, now that I think about it, i'm not sure that it's a good idea - I could just set up nextcloud or use dropbox instead. Especially as i'm not sure that /config/addons_config/tandoor_recipes is the best location for all your config files. 

I have not tested these changes, so please don't merge the request yet. If I find time another day I may look at testing, but I don't have an environment suitable for testing at the moment.

## disable debug mode
Hopefully my changes to the config file have enabled the user to choose whether their installation is in debug mode or not. Again, this is untested, and my first use of addons configuration, so it may be incorrect.

### CODE REVIEW

**Comment by alexbelgium** [comment]
Hi, thanks for your PR! Is this in a ready state for merging ?

**Comment by nough** [comment]
Afraid I don't know - I probably should have forked from your test
repository first. It seems to have failed two actions in your automated
workflow.

I won't have another chance to look at it until at least Friday, probably
next week

**Comment by alexbelgium** [comment]
Thanks! Take the time that you need, just checking. The failed checks are not very important from what I checked

**Comment by nough** [comment]
Managed to get a test environment up and running using vscode and devcontainers. I've not yet managed to test these two features, but i'll look to do that this weekend.

**Comment by nough** [comment]
Didn't succeed in any of my tests. May just be my laptop. It'll be another week before I get a chance to test properly, sadly. I can cancel the PR and work on it in my own branch if you'd prefer?

**Comment by alexbelgium** [comment]
As you want, you can leave that here for the moment there is no impact. Good luck!

**Comment by nough** [comment]
I think i'm doing something very wrong with devcontainers, but I don't know what - I think i've narrowed it down to not actually recompiling the code when I do tests? I just tried to make some changes to add 
```
export DEBUG=$(bashio::config 'DEBUG') && bashio::log.blue "DEBUG=$DEBUG"
```
to line 11 of 99-run.sh, but it didn't show up in blue in the tandoor log when I rebuilt the container. do I need to rebuild and clear cache?

**Comment by alexbelgium** [comment]
> I think i'm doing something very wrong with devcontainers, but I don't know what - I think i've narrowed it down to not actually recompiling the code when I do tests? I just tried to make some changes to add
> 
> ```
> export DEBUG=$(bashio::config 'DEBUG') && bashio::log.blue "DEBUG=$DEBUG"
> ```
> 
> to line 11 of 99-run.sh, but it didn't show up in blue in the tandoor log when I rebuilt the container. do I need to rebuild and clear cache?

Hi, if you have the `image` tag in config.json perhaps it still pulls the upstream image and does not implement your code. It took me a long time to figure that out. If this is the case, you need to remove that tag for as long as you do the tests to have a local build

**Comment by nough** [comment]
Removing the `image` tag has sorted it, I'm now able to boot in normal non-debug mode. I have also successfully tested local externalfiles, I merged another change to sort out publishing the environment variable, and now I think it's ready to go.

**Comment by alexbelgium** [comment]
Thanks!

**Pull request merged**
