### PR TITLE
[KOMETA] Replace of plex-meta-manager

### PR DESCRIPTION
**Pull request by akrigator**
https://github.com/alexbelgium/hassio-addons/issues/1357

### CODE REVIEW

**Comment by alexbelgium** [comment]
Hi, thanks very much! Really appreciate

**Comment by alexbelgium** [comment]
And thanks very much for studying the logic of build (including the path_filters.yaml) file and including all that in your PR !

**Comment by akrigator** [comment]
Shame on me, i've thought that it will published after merge to upstream, since my clone does not have configured token
image

**Comment by alexbelgium** [comment]
Hi, it should have published after merge, but it failed as the referenced armv7 image in build.json doesn't seem to exist, I've corrected that

**Comment by alexbelgium** [comment]
Now the build had worked and you should be able to install!

**Comment by akrigator** [comment]
Yeah!! it's alive!! Thanks you so much for assistance

**Pull request merged**
