### PR TITLE
WHATSAPPER | Fixed WWeb.js library

### PR DESCRIPTION
**Pull request by baldarn**
fixing using a PR branch that should work

https://github.com/pedroslopez/whatsapp-web.js/pull/2816

### CODE REVIEW

**Comment by siw1973** [comment]
@baldarn let me know when it's pushed and I'll try when I'm back home in about an hour 👍

**Comment by siw1973** [comment]
@baldarn looks like it's passed the login and polling for messages, I'm assuming that the Web UI won't open until it's completed ? Is it loading all of my historic messages ?

**Comment by siw1973** [comment]
I'm not sure if all is well. Following on from the above I'm getting the following which I think is causing the Web UI to fail.

`{"level":30,"time":1714417316546,"pid":7,"hostname":"db21ed7f-whatsapper","reqId":"req-8","msg":"Route GET:/favicon.ico not found"}`

**Comment by siw1973** [comment]
However I can get to 192.168.2.156:4000/chats

I have also set up the following in configuration.yaml

  - platform: Whatsapper
    name: "y4_mc_login"
    chat_id: xxxxxxxxxxxxx@g.us

But this does not create a Service that is available in HA such as notify.y4_mc_login

TBH I'm blundering around a bit blind here and taking two steps forward and two steps back.....

**Comment by baldarn** [comment]
@siw1973 strange.

now my instance of whatsapper is working. did you reboot the system after adding the configuration? you cannot create or edit it without rebooting home assistant :)

**Comment by baldarn** [comment]
hold on, did you installed the whatsapper home assistant integration via hacs?

https://github.com/baldarn/whatsapper-ha-integration

**Comment by siw1973** [comment]
> @siw1973 strange.
> 
> now my instance of whatsapper is working. did you reboot the system after adding the configuration? you cannot create or edit it without rebooting home assistant :)


1/ Yes I did install via HACS, but after a VM restart couldn't access anything at http://192.168.2.156:5000 so I found the above URL after digging around.

2/ After accessing on http://192.168.2.156:5000/chats I found the Group ID I want to send to and modify configuration.yaml as above and Restarted Home Assistant services.

3/ After doing this I have been looking for an appropriate Notify Service in Developer Tools to call within my existing Automations. I have notify services for mobile devices and also "platform : group" entries I have put in configuration.yaml, but not for platform : whatsapper

QUESTION : Is there another web UI page apart from http://192.168.2.156:5000/chats ? The documentation intimates I should be able to access from http://192.168.2.156:5000/ on it's own

**Comment by baldarn** [comment]
maybe the issue could be the `_`?

try renaming `name: "y4 mc login"`

then, the availabels uis are:
/chats
/qr

is still ultra basic for now.

the favicon is a bug i think, but shouldn't be a problem

**Comment by siw1973** [comment]
Hi there, still no joy. My full Notify part on configuration.yaml is as follows : 

```
# Notification Groups
notify:
  - name: "notify_ha_core"
    platform: group
    services:
    - service: mobile_app_sjw_pixel7
    - service: mobile_app_mtfr_pixel7
  - name: "notify_ha_parents"
    platform: group
    services:
    - service: mobile_app_dsb_0230
  - name: "y4mclogin"
    platform: Whatsapper
    chat_id: 120363291964404121@g.us
```

1/ Is this supposed to create a notify service that I can access from Developer Tools -> Services ?

2 / I have found a Device for Whatsapper, but no corresponding Entities that I could hang a Service from : 

image

image

**Comment by baldarn** [comment]
services
Screenshot_20240430_162057

config
Screenshot_20240430_162203

devices
Screenshot_20240430_162239

it seems you are missing the HACS integration

**Comment by siw1973** [comment]
OK, I said I needed a step by step guide 😂

I now have version 2024.2.6 of the Integration installed, but still not working.

Is there an order these need to be installed in?

I.E. Integration and then Add On?

**Comment by siw1973** [comment]
I have installed and reloaded the HACS Integration, wiped everything and then rebuilt from scratch, removed the config.yaml entries and reloaded and I cannot get the Whatsapper-Notification device to display.

Can you please provide guidance on how I can wipe everything and then the steps to intall from nothing.

**Comment by baldarn** [comment]
tomorrow I'll assist you.

if needed, we can schedule a call ;)

**Comment by baldarn** [comment]
@siw1973 I tried to delete everything and go on.

can you check that in `/custom_components/` there is a folder named `whatsapper`?

if not, you are having problem installing the integration from HACS

**Comment by siw1973** [comment]
Hi there, unfortunately I'm not on Telegram.

I did have a folder called Whatsapper previously. As I've deleted everything lets start from scratch, step by step.

- What do I install first. The Add On or the Integration.

**Comment by baldarn** [comment]
that should be the same.

try to install first the addon, then the integration

then add the configuration 

then restart home assistant

**Comment by siw1973** [comment]
So from a Devices perspective I should get the Whatsapper HA Add-ons line after installing the Add On and then after installing the Whatsapper Integration I should get the Whatsapper Notification baldarn line.

**Comment by siw1973** [comment]
Should I start the Whatsapper Add On after installing and link to Whatsapp before installing the Whatsapper Integration.

Step by step :-)

**Comment by baldarn** [comment]
I did that without starting the addon. so try without

**Comment by siw1973** [comment]
> So from a Devices perspective I should get the Whatsapper HA Add-ons line after installing the Add On and then after installing the Whatsapper Integration I should get the Whatsapper Notification baldarn line.

Is this correct ?

**Comment by siw1973** [comment]
I haven't started the AddOn yet, but the Whatsapper notification line is not visible in devices.

image

**Comment by siw1973** [comment]
I do have the Whatsapper folder present under custom components though 👍 

image

**Comment by baldarn** [comment]
could we do a call? maybe we can solve this in 5 mins ;)

tell me your preferred call system

**Comment by siw1973** [comment]
Hi there, just been setting up accounts on an old email address.

I've pinged you an email.

**Comment by siw1973** [comment]
Your email just bounced..... 

lorenzo@farnararo.it

**Comment by baldarn** [comment]
try lorenzo.farnararo@gmail.com

**Comment by baldarn** [comment]
we should have fixed that! ;)

**Comment by alexbelgium** [comment]
Thanks very much @baldarn !!! And great to know it is solved!!

**Pull request merged**
