### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by bruvv**
When there is a date in the version line inthe changelog.MD hassio isnt picking it up. changed it.

### CODE REVIEW

**Comment by alexbelgium** [comment]
You closed it?

**Comment by alexbelgium** [comment]
I was just going to merge :)

**Comment by bruvv** [comment]
Ah yea this was with changed stuff in the changelog which will be aligned tonight. So instead of redoing all those edit I am working on just the config url fixes and will do a new PR with just them fixed.

**Comment by alexbelgium** [comment]
OK thanks!

**Pull request closed without merging**
