### PR TITLE
Changed new upstream versions

### PR DESCRIPTION
**Pull request by bruvv**
Also added missing changelogs from the past few comments :)

### CODE REVIEW

**Comment by alexbelgium** [comment]
Hi, I'm outside for the moment and not near a usable github but actually the "upstream" code is automatically updated every Monday, Wednesday and Friday according to the addons_updated addon that runs on my rpi!

The logic is that the addon checks if the tag "upstream" is aligned with the latest release on github (or dockerfile). It does not look the tag "version". If there is a new release, it updates the tag "upstream" in 3 files if relevant : config.json, build.json and Dockerfile, and aligns the tag "version" with the new upstream. This allows to have a dockerfile for example with : ```BUILD_FROM name/name:$UPSTREAM```

If you update it manually, you need to make sure that all instances are changed, as the addons_updater works with sed to replace the tag. So if somewhere the tag upstream does not corresponds to the one in config.json, it will not be updated by my automatic script.

However, I usually link the docker build to "latest". This allows people to always have the latest version, even if my script did not update the version. This avoids issues if for example, the dockerhub image upstream is not named the same way as the github releases.

Hope it clarifies :)

I'll look at all your commits a bit later today! Thanks for the commits!

**Comment by alexbelgium** [comment]
In the same way, my addons_updater script does not take into account the part after -ls in the upstream versions. Only the part to the left corresponds to the app version, the number after - ls corresponds to improvements made by the linuxserver team that manages some upstream image (for example, an automatic dependence update - useless for us as we are building from the docker image)

**Comment by alexbelgium** [comment]
Thanks!

**Comment by bruvv** [comment]
awesome didnt know that! thanks for explaining. How is the changelog populated? Is that also done by the addon? It should include the very specific version number.

**Comment by alexbelgium** [comment]
Yes :) actually there is a high probability that all files realign this night when then addon runs, we'll see tomorrow. It works pretty well :)

**Pull request merged**
