### PR TITLE
Update Config Location

### PR DESCRIPTION
**Pull request by kool2zero**
Fix misspelling in config location.

image

### CODE REVIEW

**Comment by alexbelgium** [comment]
Hi, thanks we'll also need to transfer files for users : check if the previous location had files in it and transfer it to the corrected folder name then remove the previous folder name 

Also you'll need to Increment the version in config.yaml ( I use -2 usually) for a new build to launch. Thanks!

**Comment by kool2zero** [comment]
I pushed the updated code based on your feedback,

**Comment by alexbelgium** [comment]
Thanks!

**Comment by alexbelgium** [comment]
Really nice

**Pull request merged**
