### PR TITLE
Aligned config with upstream

### PR DESCRIPTION
**Pull request by bruvv**
added homeassistant example

### CODE REVIEW

**Comment by alexbelgium** [comment]
Hi, thanks, it seems to be an invalid json though as ’//’ comments are not accepted I think in json ? Or does the app allows this ?

**Comment by bruvv** [comment]
It is a config example that people should adjust anyway otherwise the app will not work. I will see what I can do to change it to a gui and fix the linting.

**Comment by bruvv** [comment]
@alexbelgium the linting is not something I seem to understand. Can you have a look ?

**Comment by alexbelgium** [comment]
I've learned by myself so it could be incorrect, but linting is to see if the code is aligned with standard. It checks automatically every code update to see if it conforms, is there is a red cross. For json, here is an external linter to check validity : https://jsonlint.com/

Clicking on the red cross next to your commits, you should see the linting performed and the pointers to solve it

Hope this helps!

**Comment by alexbelgium** [comment]
Actually having checked the GitHub action log I think it's more the appearance of passwords on the json (even fake) that trigger a GitLeak alarm

**Comment by bruvv** [comment]
@alexbelgium correct: https://github.com/alexbelgium/hassio-addons/actions/runs/3355107407/jobs/5559129204 this is because of false positive so we can ignore this.
But this: https://github.com/alexbelgium/hassio-addons/actions/runs/3355107404/jobs/5559129826 I do not understand, it is saying probably that I am using tabs instead of spaces which is not true since I am always using 2 spaces instead of 1 tab.

**Comment by alexbelgium** [comment]
> @alexbelgium correct: https://github.com/alexbelgium/hassio-addons/actions/runs/3355107407/jobs/5559129204 this is because of false positive so we can ignore this. But this: https://github.com/alexbelgium/hassio-addons/actions/runs/3355107404/jobs/5559129826 I do not understand, it is saying probably that I am using tabs instead of spaces which is not true since I am always using 2 spaces instead of 1 tab.

It's strange, I do see one tab and not two spaces. I've changed it in the config.json above for example

To ignore gitleaks I'll check how to do that

**Comment by alexbelgium** [comment]
I'll merge it, we'll manage gitleaks afterwards ;) thanks!

**Pull request merged**
