### PR TITLE
adding more options for gitea (support requested)

### PR DESCRIPTION
**Pull request by baldarn**
hi @alexbelgium ,
I'm trying to solve the https://github.com/alexbelgium/hassio-addons/issues/474 for the ssl.

I was also trying to add some options to better edit the add on from hassio configuration page.

I'm kind of in pain here. I get that you have some best practices, but being a bit noob with docker and pretty young with the project I feel like I would do more damage that good things :'(

Can you give me some advice on how you would address this? in this PR I tried something, but I somehow override the /data folder that the base image of gitea automatically have. this happends adding the automatic scripts that I find in lots of addon, but I don't know where that happens :/

I'm sorry to bother you, but I tried for some hours and got nothing much :(

### CODE REVIEW

**Comment by alexbelgium** [comment]
Hi, I really don't have much time for the moment I'll check this weekend! Thanks

**Comment by alexbelgium** [comment]
Hi, you were nearly there. I've looked at the gitea code and changed the last line of the run.sh to execute their entrypoint, then use sed to modify the app.ini. I haven't tested it though yet

**Comment by alexbelgium** [comment]
It's slightly better but still the new values pushed in the app.ini don't seem to be considered... I'll have to look a bit deeper except if you have other ideas?

**Comment by baldarn** [comment]
thanks for the work! I'll try to find some time to test it... maybe tonight... :ocean:

**Comment by alexbelgium** [comment]
> thanks for the work! I'll try to find some time to test it... maybe tonight... 🌊

Honestly I hadn't the time to really test it also, just saw that the code allowed to launch but that the new configs were not taken into account...

**Comment by alexbelgium** [comment]
Hopefully it is fine now

**Comment by alexbelgium** [comment]
Hi, should I merge it? Thanks!

**Comment by baldarn** [comment]
the ssl is working, I would like to add the other vars in the file and then we can merge it ;)

**Comment by baldarn** [comment]
forget about it... I tried editing the confs and the start engine of gitea doesn't take care of it... let's leave those edit manually in the confs for now :/

**Comment by alexbelgium** [comment]
"I tried editing the confs and the start engine of gitea doesn't take care of it..." indeed, even though the values are added in the app.ini they don't seem to be read

**Comment by alexbelgium** [comment]
I've got it : at first runs it takes only variables from /etc/s6/gitea.
I've added them as sed and I'm pretty sure it should work

**Comment by baldarn** [comment]
there is a problem with the version number...meh... tell me if it's ok like this or we have to bump it. consider that I was folliwing the version number of the original gitea project :/

**Comment by alexbelgium** [comment]
> there is a problem with the version number...meh... tell me if it's ok like this or we have to bump it. consider that I was folliwing the version number of the original gitea project :/

For version number you can add what you prefer, there is no specificities. Anyway It will be overwritten at next automatic update. As long as there is a change vs the current number, to allow HA to detect the new version

**Comment by baldarn** [comment]
ok, I changed it, but I see that the check for updated fails. I set ```x.y.z.v``` because `x.y.z` is for the gitea reference and `v` is for the plugin... the tests are not passing :/

**Comment by alexbelgium** [comment]
Don't worry about that, actually I use those tests more as a safeguard than a requirement :) I'll merge it! Let's see how that goes!

**Comment by alexbelgium** [comment]
Does it work for you ? It doesn't load on my side...

**Comment by baldarn** [comment]
is working for me. Maybe you changed the port? I saw that changing the port from 3000 to another doesn't work... :/

**Comment by alexbelgium** [comment]
I've pushed a final version that works, and automatically calculates the root url if it is not encoded manually based on the domain option

**Pull request merged**
